version: '3.9'

services:
  web:
    container_name: 'aspnetcoreapp'
    build:
      context: ./kanban-webapp
    ports:
      - "5000:5000"
    depends_on:
      - "postgres"
    networks:
      - aspnetcoreapp-network

  postgres:
    container_name: 'postgres'
    image: postgres
    environment:
      POSTGRES_DB: "kanban"
      POSTGRES_USER: "kanban-user"
      POSTGRES_PASSWORD: "test-password"
    ports: 
      - 6565:5432
    networks:
      - aspnetcoreapp-network

  front:
    build: ./app-kanban-board
    ports:
      - "9999:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - aspnetcoreapp-network
    depends_on:
      - web

networks:
  aspnetcoreapp-network:
    driver: bridge
