// <auto-generated />
using System;
using Kanban.Db.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace kanban_webapp.Migrations
{
    [DbContext(typeof(BoardContext))]
    [Migration("20240324135609_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kanban.Model.Entity.BoardEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("Kanban.Model.Entity.CardEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("ColumnEntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ColumnEntityId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("Kanban.Model.Entity.ColumnEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("BoardEntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BoardEntityId");

                    b.ToTable("Columns");
                });

            modelBuilder.Entity("Kanban.Model.Entity.UserEntity", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.Property<long?>("BoardEntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.HasKey("UserName");

                    b.HasIndex("BoardEntityId");

                    b.ToTable("UserEntity");
                });

            modelBuilder.Entity("Kanban.Model.Entity.CardEntity", b =>
                {
                    b.HasOne("Kanban.Model.Entity.ColumnEntity", null)
                        .WithMany("Cards")
                        .HasForeignKey("ColumnEntityId");
                });

            modelBuilder.Entity("Kanban.Model.Entity.ColumnEntity", b =>
                {
                    b.HasOne("Kanban.Model.Entity.BoardEntity", null)
                        .WithMany("Columns")
                        .HasForeignKey("BoardEntityId");
                });

            modelBuilder.Entity("Kanban.Model.Entity.UserEntity", b =>
                {
                    b.HasOne("Kanban.Model.Entity.BoardEntity", null)
                        .WithMany("Users")
                        .HasForeignKey("BoardEntityId");
                });

            modelBuilder.Entity("Kanban.Model.Entity.BoardEntity", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Kanban.Model.Entity.ColumnEntity", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
